apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xgpib6ynv-nodejs 
  janus-idp.io/tekton: xgpib6ynv-nodejs
  backstage.io/kubernetes-id: xgpib6ynv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgpib6ynv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml